apiVersion: v1
kind: Namespace
metadata:
  name: manifestsio
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: manifestsio
  namespace: manifestsio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manifestsio
  template:
    metadata:
      labels:
        app: manifestsio
    spec:
      containers:
        - name: manifestsio
          image: <IMAGE>
          ports:
            - containerPort: 3000
          env:
            # PostHog Analytics
            - name: NEXT_PUBLIC_POSTHOG_KEY
              value: "phc_aur20epnEcOsmKpTpdbPMjJSzM5ypEtSD4zLwm0Q0aD"
            - name: NEXT_PUBLIC_POSTHOG_HOST
              value: "https://g.theoutdoorprogrammer.com"
---
apiVersion: v1
kind: Service
metadata:
  name: manifestsio
  namespace: manifestsio
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: manifestsio